// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	createProject: (request: CreateProjectRequest) => typedError<UiProjectSnapshot, AppError>(__TAURI_INVOKE("create_project", { request })),
	openProject: (rootPath: string, mainFile: string | null) => typedError<UiProjectSnapshot, AppError>(__TAURI_INVOKE("open_project", { rootPath, mainFile })),
	openProjectWindow: (rootPath: string, mainFile: string | null) => typedError<OpenedProjectWindow, AppError>(__TAURI_INVOKE("open_project_window", { rootPath, mainFile })),
	readProject: (sessionId: ProjectSessionId) => typedError<UiProjectSnapshot, AppError>(__TAURI_INVOKE("read_project", { sessionId })),
	closeProject: (sessionId: ProjectSessionId) => typedError<null, AppError>(__TAURI_INVOKE("close_project", { sessionId })),
	applySourceEdits: (sessionId: ProjectSessionId, baseRevision: Revision, edits: SourceEdit[]) => typedError<UiEditResult, AppError>(__TAURI_INVOKE("apply_source_edits", { sessionId, baseRevision, edits })),
	applyDocumentOp: (sessionId: ProjectSessionId, baseRevision: Revision, operation: DocumentOp) => typedError<UiEditResult, AppError>(__TAURI_INVOKE("apply_document_op", { sessionId, baseRevision, operation })),
	prepareUtf8Conversion: (sessionId: ProjectSessionId, fileId: FileId) => typedError<Utf8ConversionPreview, AppError>(__TAURI_INVOKE("prepare_utf8_conversion", { sessionId, fileId })),
	convertFileToUtf8: (sessionId: ProjectSessionId, baseRevision: Revision, fileId: FileId, reviewedText: string, expectedOriginalSha256: string) => typedError<UiEditResult, AppError>(__TAURI_INVOKE("convert_file_to_utf8", { sessionId, baseRevision, fileId, reviewedText, expectedOriginalSha256 })),
	saveProject: (sessionId: ProjectSessionId, expectedRevision: Revision) => typedError<UiSaveResult, AppError>(__TAURI_INVOKE("save_project", { sessionId, expectedRevision })),
	searchLocalCitations: (sessionId: ProjectSessionId, fileId: FileId, query: string) => typedError<LocalCitationSearch, CitationCommandError>(__TAURI_INVOKE("search_local_citations", { sessionId, fileId, query })),
	upsertBibliographyEntry: (sessionId: ProjectSessionId, baseRevision: Revision, fileId: FileId, draft: BibEntryDraft) => typedError<UiEditResult, CitationCommandError>(__TAURI_INVOKE("upsert_bibliography_entry", { sessionId, baseRevision, fileId, draft })),
	deleteBibliographyEntry: (sessionId: ProjectSessionId, baseRevision: Revision, fileId: FileId, key: string) => typedError<UiEditResult, CitationCommandError>(__TAURI_INVOKE("delete_bibliography_entry", { sessionId, baseRevision, fileId, key })),
	renameCitationKey: (sessionId: ProjectSessionId, baseRevision: Revision, bibliographyFileId: FileId, oldKey: string, newKey: string) => typedError<UiEditResult, CitationCommandError>(__TAURI_INVOKE("rename_citation_key", { sessionId, baseRevision, bibliographyFileId, oldKey, newKey })),
	lookupCitationMetadata: (sessionId: ProjectSessionId, request: MetadataLookupRequest) => typedError<MetadataLookupResponse, CitationCommandError>(__TAURI_INVOKE("lookup_citation_metadata", { sessionId, request })),
	getRuntimeReadiness: () => __TAURI_INVOKE<RuntimeReadiness>("get_runtime_readiness"),
	startCompile: (sessionId: ProjectSessionId, revision: Revision, engine: LatexEngine) => typedError<CompileTicket, AppError>(__TAURI_INVOKE("start_compile", { sessionId, revision, engine })),
	cancelCompile: (sessionId: ProjectSessionId, jobId: CompileJobId) => typedError<null, AppError>(__TAURI_INVOKE("cancel_compile", { sessionId, jobId })),
	readCompilePdf: (sessionId: ProjectSessionId) => typedError<UiPdfArtifact, AppError>(__TAURI_INVOKE("read_compile_pdf", { sessionId })),
	listHistory: (sessionId: ProjectSessionId) => typedError<UiHistoryEntry[], AppError>(__TAURI_INVOKE("list_history", { sessionId })),
	createSnapshot: (sessionId: ProjectSessionId, name: string | null) => typedError<UiHistoryEntry, AppError>(__TAURI_INVOKE("create_snapshot", { sessionId, name })),
	restoreSnapshot: (sessionId: ProjectSessionId, snapshotId: SnapshotId) => typedError<UiProjectSnapshot, AppError>(__TAURI_INVOKE("restore_snapshot", { sessionId, snapshotId })),
	/**
	 *  The runtime service owns network/process access. Until its signed profile
	 *  and platform sandbox attestation are wired, the public boundary fails
	 *  closed rather than producing a misleading artifact.
	 */
	runArxivPreflight: (sessionId: ProjectSessionId, revision: Revision) => typedError<ArxivPreflightReportV1_Serialize, AppError>(__TAURI_INVOKE("run_arxiv_preflight", { sessionId, revision })),
	exportArxiv: (sessionId: ProjectSessionId, revision: Revision, destination: string) => typedError<ExportResult, AppError>(__TAURI_INVOKE("export_arxiv", { sessionId, revision, destination })),
};

/** Events */
export const events = {
	setwrightCompileEvent: makeEvent<CompileEventEnvelope>("setwright-compile-event"),
};

/* Types */
/**
 *  A stable, structured error contract suitable for the Tauri boundary.
 * 
 *  Variants intentionally carry strings instead of `std::io::Error` so the
 *  value can be serialized without losing its category.  Internal errors are
 *  converted at the point where enough operation/path context is available.
 */
export type AppError = { kind: "io"; operation: string; path: string; message: string } | { kind: "invalidUtf8"; path: string } | { kind: "invalidPath"; path: string; message: string } | { kind: "pathOutsideRoot"; path: string } | { kind: "capabilityDenied"; capability: string; message: string } | { kind: "fileNotFound"; path: string } | { kind: "unknownFile"; file_id: string } | { kind: "sessionClosed" } | { kind: "revisionConflict"; expected: number; actual: number } | { kind: "hashMismatch"; expected: string; actual: string } | { kind: "invalidEdit"; reason: string } | { kind: "invalidProject"; message: string } | { kind: "parse"; message: string } | { kind: "serialization"; message: string } | { kind: "externalConflict"; path: string } | { kind: "preflightBlocked"; message: string } | { kind: "compileUnavailable"; message: string } | { kind: "archive"; message: string };

export type ArxivCleanBuild = {
	succeeded: boolean,
	startedAt: string,
	finishedAt: string,
	pdfSha256: string | null,
	pageCount: number | null,
};

export type ArxivExcludedFile = {
	path: string,
	reason: string,
};

export type ArxivFinding = ArxivFinding_Serialize | ArxivFinding_Deserialize;

export type ArxivFindingSeverity = "info" | "warning" | "blocker";

export type ArxivFinding_Deserialize = {
	id: string,
	severity: ArxivFindingSeverity,
	code: string,
	message: string,
	path: string | null,
	line: number | null,
};

export type ArxivFinding_Serialize = {
	id: string,
	severity: ArxivFindingSeverity,
	code: string,
	message: string,
	path?: string | null,
	line?: number | null,
};

export type ArxivIncludedFile = {
	path: string,
	sizeBytes: number,
	sha256: string,
};

export type ArxivPolicy = {
	policyId: string,
	submissionToolsCommit: string | null,
};

export type ArxivPreflightReportV1 = ArxivPreflightReportV1_Serialize | ArxivPreflightReportV1_Deserialize;

export type ArxivPreflightReportV1_Deserialize = {
	schemaVersion: number,
	reportId: string,
	generatedAt: string,
	source: ArxivSource,
	runtime: ArxivRuntime,
	policy: ArxivPolicy,
	findings: ArxivFinding_Deserialize[],
	includedFiles: ArxivIncludedFile[],
	excludedFiles: ArxivExcludedFile[],
	cleanBuild: ArxivCleanBuild,
	userApproval: ArxivUserApproval,
	ready: boolean,
};

export type ArxivPreflightReportV1_Serialize = {
	schemaVersion: number,
	reportId: string,
	generatedAt: string,
	source: ArxivSource,
	runtime: ArxivRuntime,
	policy: ArxivPolicy,
	findings: ArxivFinding_Serialize[],
	includedFiles: ArxivIncludedFile[],
	excludedFiles: ArxivExcludedFile[],
	cleanBuild: ArxivCleanBuild,
	userApproval: ArxivUserApproval,
	ready: boolean,
};

export type ArxivRuntime = {
	profileId: string,
	manifestSha256: string,
	engine: LatexEngine,
};

export type ArxivSource = {
	projectId: ProjectId,
	revision: Revision,
	mainFile: string,
	sourceSha256: string,
};

export type ArxivUserApproval = {
	approved: boolean,
	approvedAt: string | null,
	approvedPdfSha256: string | null,
};

export type BibEntryDraft = {
	entryType: string,
	key: string,
	/**  Plain LaTeX values. The formatter wraps each value in braces. */
	fields: { [key in string]: string },
};

export type BibFinding = {
	severity: BibFindingSeverity,
	code: string,
	message: string,
	entryKey: string | null,
	span: TextSpan,
};

export type BibFindingSeverity = "warning" | "error";

export type BibSearchResult = {
	key: string,
	entryType: string,
	title: string | null,
	authors: string | null,
	year: string | null,
	score: number,
	span: TextSpan,
};

export type CitationAuthor = {
	given: string | null,
	family: string | null,
	literal: string,
};

export type CitationCommandError = { kind: "app"; error: AppError } | { kind: "citation"; error: CitationError };

export type CitationError = { kind: "parserUnavailable"; message: string } | { kind: "invalidEdit"; message: string } | { kind: "keyNotFound"; key: string } | { kind: "ambiguousKey"; key: string } | { kind: "duplicateKey"; key: string } | { kind: "unsafeCitationSyntax"; path: string; at_byte: number } | { kind: "invalidQuery"; message: string } | { kind: "endpointRejected"; url: string } | { kind: "redirectRejected"; url: string } | { kind: "network"; message: string } | { kind: "httpStatus"; status: number } | { kind: "responseTooLarge"; limit_bytes: number } | { kind: "invalidResponse"; message: string };

export type CitationMetadata = {
	provider: MetadataProvider,
	providerId: string,
	workType: CitationWorkType,
	title: string,
	authors: CitationAuthor[],
	issuedYear: number | null,
	venue: string | null,
	abstractText: string | null,
	doi: string | null,
	arxivId: string | null,
	url: string | null,
};

export type CitationWorkType = "article" | "conferencePaper" | "book" | "thesis" | "preprint" | "other";

export type CompatibilitySeverity = "info" | "warning" | "blocked";

export type CompileEvent = { kind: "queued"; job_id: CompileJobId; revision: Revision } | { kind: "started"; job_id: CompileJobId; revision: Revision } | { kind: "log"; job_id: CompileJobId; stream: LogStream; text: string; truncated: boolean } | { kind: "diagnostic"; job_id: CompileJobId; diagnostic: Diagnostic } | { kind: "finished"; job_id: CompileJobId; revision: Revision; success: boolean; pdf_hash: string | null; stale: boolean } | { kind: "cancelled"; job_id: CompileJobId };

export type CompileEventEnvelope = {
	sessionId: ProjectSessionId,
	event: CompileEvent,
};

export type CompileJobId = string;

export type CompileTicket = {
	jobId: CompileJobId,
	revision: Revision,
	state: string,
};

export type CreateProjectRequest = {
	parentDirectory: string,
	folderName: string,
	title: string,
	authors?: string[],
	templateId: TemplateId,
	engine: LatexEngine,
};

export type Diagnostic = {
	code: string,
	severity: DiagnosticSeverity,
	category: DiagnosticCategory,
	title: string,
	message: string,
	span: SourceSpan | null,
	sourceLine: number | null,
	actions?: DiagnosticAction[],
	technicalDetail: string | null,
};

export type DiagnosticAction = {
	actionId: string,
	label: string,
	safe: boolean,
};

export type DiagnosticCategory = "syntax" | "missingDependency" | "unsafePath" | "unsupportedFeature" | "compile" | "bibliography" | "arxivPolicy" | "internal";

export type DiagnosticSeverity = "info" | "warning" | "error" | "blocker";

export type DocumentNode = {
	nodeKind: VisualNodeKind,
	/**
	 *  Canonical LaTeX for a newly inserted node. Existing source is never
	 *  regenerated from this representation.
	 */
	latex: string,
	attributes?: { [key in string]: string },
};

/**
 *  Semantic intent sent by the visual editor. The command adapter resolves an
 *  operation into one or more `SourceEdit`s and then submits those edits to the
 *  revision-checked canonical source engine.
 */
export type DocumentOp = { kind: "insertText"; file_id: FileId; at_byte: number; text: string } | { kind: "replaceText"; span: SourceSpan; replacement: string; expected_slice_hash: string } | { kind: "delete"; span: SourceSpan; expected_slice_hash: string } | { kind: "setMark"; span: SourceSpan; mark: TextMark; enabled: boolean } | { kind: "insertNode"; file_id: FileId; at_byte: number; node: DocumentNode } | { kind: "setAttribute"; span: SourceSpan; name: string; value: string | null } | { kind: "move"; span: SourceSpan; destination_byte: number; expected_slice_hash: string };

export type ExportResult = {
	archivePath: string,
	reportPath: string,
	archiveHash: string,
};

export type FileId = string;

export type LatexEngine = "pdflatex" | "xelatex";

export type LocalCitationSearch = {
	fileId: FileId,
	sourceHash: string,
	hasParseErrors: boolean,
	findings: BibFinding[],
	results: BibSearchResult[],
};

export type LocalDocument = {
	path: string,
	sha256: string,
};

export type LogStream = "stdout" | "stderr";

export type LookupTrigger = "explicitUserAction";

export type MetadataLookupRequest = {
	provider: MetadataProvider,
	query: string,
	maxResults: number,
	trigger: LookupTrigger,
};

export type MetadataLookupResponse = {
	provider: MetadataProvider,
	query: string,
	results: CitationMetadata[],
	truncated: boolean,
};

export type MetadataProvider = "crossref" | "arxiv";

export type OpenedProjectWindow = {
	windowLabel: string,
	sessionId: ProjectSessionId,
};

export type PaperSettingsV1 = {
	schemaVersion: number,
	projectId: ProjectId,
	mainFile: string,
	templateId: TemplateId,
	runtimeId: string,
	engine: LatexEngine,
};

export type ProjectEvent = { kind: "opened"; session_id: ProjectSessionId; root: string; main_file_id: FileId; revision: Revision } | { kind: "revisionChanged"; revision: Revision; files: FileId[] } | { kind: "saved"; revision: Revision; files: FileId[] } | { kind: "externalReloaded"; file_id: FileId; revision: Revision } | { kind: "externalConflict"; file_id: FileId; relative_path: string } | { kind: "closed" };

export type ProjectId = string;

export type ProjectSessionId = string;

export type ReviewAnchor = {
	fileId: string,
	startByte: number,
	endByte: number,
	baseFileHash: string,
	expectedSource: string,
	prefixContext: string,
	suffixContext: string,
};

export type ReviewBaseFile = {
	fileId: string,
	path: string,
	sha256: string,
	byteLength: number,
};

export type ReviewBundleV1 = ReviewBundleV1_Serialize | ReviewBundleV1_Deserialize;

export type ReviewBundleV1_Deserialize = {
	schemaVersion: number,
	bundleId: string,
	projectId: ProjectId,
	projectHash: string,
	baseFiles: ReviewBaseFile[],
	reviewer: ReviewIdentity_Deserialize,
	exportedAt: string,
	threads: ReviewThread_Deserialize[],
	suggestions: ReviewSuggestion_Deserialize[],
};

export type ReviewBundleV1_Serialize = {
	schemaVersion: number,
	bundleId: string,
	projectId: ProjectId,
	projectHash: string,
	baseFiles: ReviewBaseFile[],
	reviewer: ReviewIdentity_Serialize,
	exportedAt: string,
	threads: ReviewThread_Serialize[],
	suggestions: ReviewSuggestion_Serialize[],
};

export type ReviewIdentity = ReviewIdentity_Serialize | ReviewIdentity_Deserialize;

export type ReviewIdentity_Deserialize = {
	id: string,
	displayName: string,
	email: string | null,
};

export type ReviewIdentity_Serialize = {
	id: string,
	displayName: string,
	email?: string | null,
};

export type ReviewMessage = ReviewMessage_Serialize | ReviewMessage_Deserialize;

export type ReviewMessage_Deserialize = {
	id: string,
	author: ReviewIdentity_Deserialize,
	createdAt: string,
	body: string,
};

export type ReviewMessage_Serialize = {
	id: string,
	author: ReviewIdentity_Serialize,
	createdAt: string,
	body: string,
};

export type ReviewSuggestion = ReviewSuggestion_Serialize | ReviewSuggestion_Deserialize;

export type ReviewSuggestion_Deserialize = {
	id: string,
	order: number,
	author: ReviewIdentity_Deserialize,
	createdAt: string,
	anchor: ReviewAnchor,
	replacement: string,
	status: SuggestionStatus,
};

export type ReviewSuggestion_Serialize = {
	id: string,
	order: number,
	author: ReviewIdentity_Serialize,
	createdAt: string,
	anchor: ReviewAnchor,
	replacement: string,
	status: SuggestionStatus,
};

export type ReviewThread = ReviewThread_Serialize | ReviewThread_Deserialize;

export type ReviewThreadStatus = "open" | "resolved";

export type ReviewThread_Deserialize = {
	id: string,
	anchor: ReviewAnchor,
	status: ReviewThreadStatus,
	createdAt: string,
	resolvedAt: string | null,
	messages: ReviewMessage_Deserialize[],
};

export type ReviewThread_Serialize = {
	id: string,
	anchor: ReviewAnchor,
	status: ReviewThreadStatus,
	createdAt: string,
	resolvedAt?: string | null,
	messages: ReviewMessage_Serialize[],
};

export type Revision = number;

export type RuntimeArchitecture = "x86_64" | "aarch64";

export type RuntimeArtifact = {
	url: string,
	sizeBytes: number,
	sha256: string,
};

export type RuntimeManifestV1 = {
	schemaVersion: number,
	profileId: string,
	texLiveSnapshot: TexLiveSnapshot,
	platform: RuntimePlatform,
	architecture: RuntimeArchitecture,
	engines: LatexEngine[],
	archive: RuntimeArtifact,
	signature: RuntimeSignature,
	sbom: RuntimeSbom,
	licenseInventory: LocalDocument,
	createdAt: string,
};

export type RuntimePlatform = "windows" | "macos" | "linux";

export type RuntimeReadiness = {
	profileId: string,
	runtimeManifestKeysConfigured: boolean,
	runtimeInstallAvailable: boolean,
	sandboxBackend: string | null,
	sandboxAttested: boolean,
	reason: string,
};

export type RuntimeSbom = {
	path: string,
	sha256: string,
	format: SbomFormat,
};

export type RuntimeSignature = {
	algorithm: string,
	canonicalization: string,
	keyId: string,
	value: string,
};

export type SbomFormat = "SPDX-JSON-2.3" | "CycloneDX-JSON-1.6";

export type SnapshotId = string;

export type SourceEdit = {
	fileId: FileId,
	startByte: number,
	endByte: number,
	replacement: string,
	expectedSliceHash: string,
};

export type SourceSpan = {
	fileId: FileId,
	startByte: number,
	endByte: number,
};

export type SuggestionStatus = "pending" | "accepted" | "rejected" | "conflict";

export type TemplateId = "generic-article" | "acm-acmart" | "ieee-ieeetran";

export type TexLiveSnapshot = {
	version: number,
	date: string,
};

export type TextMark = "bold" | "italic" | "monospace" | "underline" | "strike" | "superscript" | "subscript";

export type TextSpan = {
	startByte: number,
	endByte: number,
};

export type UiCompatibilityFinding = {
	id: string,
	severity: CompatibilitySeverity,
	title: string,
	detail: string,
	span: SourceSpan | null,
};

export type UiEditResult = {
	revision: Revision,
	files: UiProjectFile[],
	diagnostics: Diagnostic[],
};

export type UiHistoryEntry = {
	id: SnapshotId,
	revision: Revision,
	createdAt: string,
	label: string,
	kind: UiHistoryKind,
	changedFiles: number,
};

export type UiHistoryKind = "automatic" | "named" | "preRestore" | "preAccept";

export type UiPdfArtifact = {
	jobId: CompileJobId,
	revision: Revision,
	sha256: string,
	stale: boolean,
	/**
	 *  Typed JSON byte array for the current command surface. A raw binary IPC
	 *  response will replace this field when the frontend bridge consumes it.
	 */
	bytes: number[],
};

export type UiProjectFile = {
	id: FileId,
	relativePath: string,
	kind: UiProjectFileKind,
	encoding: UiSourceEncoding,
	content: string | null,
	dirty: boolean,
	byteLength: number,
	sha256: string,
};

export type UiProjectFileKind = "tex" | "bib" | "asset" | "style" | "other";

export type UiProjectSnapshot = {
	sessionId: ProjectSessionId,
	revision: Revision,
	rootPath: string,
	title: string,
	mainFile: FileId,
	files: UiProjectFile[],
	settings: PaperSettingsV1,
	compatibility: UiCompatibilityFinding[],
	dirty: boolean,
};

export type UiSaveResult = {
	revision: Revision,
	savedAt: string,
	fileHashes: { [key in FileId]: string },
};

export type UiSourceEncoding = "utf8" | "nonUtf8";

export type Utf8ConversionPreview = {
	fileId: FileId,
	relativePath: string,
	originalSha256: string,
	originalByteLength: number,
	reviewedText: string,
	replacementCharacterCount: number,
	utf8ByteLength: number,
	utf8Sha256: string,
};

export type VisualNodeKind = "paragraph" | "heading" | "quote" | "list" | "footnote" | "theorem" | "definition" | "proof" | "codeListing" | "citation" | "crossReference" | "inlineEquation" | "displayEquation" | "figure" | "table" | "rawInline" | "rawBlock";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

